#!/usr/bin/env python3
"""Parse docs/archive/CONSOLIDATION.md §7 into data/pending_items.jsonl.

Reads the 600-item catalog section, slugifies names and domains, filters
out items already present in catalog.yml, and writes a JSONL record per
pending instrument. Also prints stats to stdout.

Note: CONSOLIDATION.md is a historical v0.2 design document archived
under docs/archive/. catalog.yml (auto-generated by sync_catalog.py)
is the authoritative source for the current library state.
"""
from __future__ import annotations

import json
import re
import sys
import unicodedata
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CONSOLIDATION = ROOT / "docs" / "archive" / "CONSOLIDATION.md"
CATALOG = ROOT / "catalog.yml"
OUTPUT = ROOT / "data" / "pending_items.jsonl"

CLASS_MAP = {
    "L": "lens",
    "F": "frame",
    "M": "model",
    "S": "stance",
    "H": "heuristic",
}

SECTION_START_RE = re.compile(r"^##\s+7\.\s")
SECTION_END_RE = re.compile(r"^##\s+8\.\s")
DOMAIN_HEADER_RE = re.compile(r"^###\s+(.+?)\s*$")
BULLET_RE = re.compile(r"^-\s+\[([LFMSH])\]\s+(.+?)\s*$")


def slugify_name(raw: str) -> str:
    """Turn a display name into a slug.

    - remove parenthesized content (ascii + fullwidth)
    - lowercase
    - drop apostrophes
    - replace whitespace/underscores with hyphens
    - drop other non [a-z0-9-] chars
    - collapse repeated hyphens and trim
    """
    s = raw
    # Strip parenthesized content, possibly nested / multi-occurrence.
    # Iterate to handle multiple parens; also handle fullwidth ().
    prev = None
    while prev != s:
        prev = s
        s = re.sub(r"\s*\([^()]*\)", "", s)
        s = re.sub(r"\s*（[^（）]*）", "", s)
    # Transliterate diacritics: ō -> o, é -> e, etc. Non-latin scripts
    # (hangul, CJK) are left alone and filtered out by the ascii pass.
    s = unicodedata.normalize("NFKD", s)
    s = "".join(ch for ch in s if not unicodedata.combining(ch))
    s = s.lower()
    # Remove apostrophes (ascii + curly) entirely so "porter's" -> "porters".
    s = s.replace("'", "").replace("\u2019", "").replace("`", "")
    # Replace whitespace/underscore with hyphen.
    s = re.sub(r"[\s_]+", "-", s)
    # Drop any char that isn't a-z 0-9 or hyphen.
    s = re.sub(r"[^a-z0-9-]+", "-", s)
    # Collapse repeated hyphens and trim.
    s = re.sub(r"-+", "-", s).strip("-")
    return s


def slugify_domain(header: str) -> str:
    """Slugify a domain header to its first meaningful token.

    Rule: take the part before the first '/', lowercase, hyphenate
    whitespace, strip punctuation.
    """
    first = header.split("/", 1)[0]
    first = first.strip()
    first = first.lower()
    first = re.sub(r"[\s_]+", "-", first)
    first = re.sub(r"[^a-z0-9-]+", "", first)
    first = re.sub(r"-+", "-", first).strip("-")
    return first


def existing_names(catalog_path: Path) -> set[str]:
    """Extract all `- name: X` values from catalog.yml without PyYAML."""
    names: set[str] = set()
    if not catalog_path.exists():
        return names
    name_re = re.compile(r"^\s*-\s*name:\s*([A-Za-z0-9_\-]+)\s*$")
    for line in catalog_path.read_text(encoding="utf-8").splitlines():
        m = name_re.match(line)
        if m:
            names.add(m.group(1).strip())
    return names


def parse_section(md_path: Path):
    """Yield parsed records from §7 of the consolidation document.

    Each yielded tuple is (record_dict, line_number).
    """
    lines = md_path.read_text(encoding="utf-8").splitlines()
    in_section = False
    current_header: str | None = None
    current_domain: str | None = None

    for idx, line in enumerate(lines, start=1):
        if not in_section:
            if SECTION_START_RE.match(line):
                in_section = True
            continue
        if SECTION_END_RE.match(line):
            break

        dh = DOMAIN_HEADER_RE.match(line)
        if dh:
            current_header = dh.group(1).strip()
            current_domain = slugify_domain(current_header)
            continue

        bm = BULLET_RE.match(line)
        if not bm:
            continue
        if current_header is None:
            # Bullets before any ### are unexpected; skip with warning.
            print(
                f"warning: bullet at line {idx} outside a domain header; skipping",
                file=sys.stderr,
            )
            continue

        class_tag = bm.group(1)
        body = bm.group(2).strip()

        # Split display_name and one_liner on em-dash (—).
        if "—" in body:
            display_name, one_liner = body.split("—", 1)
        else:
            display_name, one_liner = body, ""
        display_name = display_name.strip()
        one_liner = one_liner.strip()

        name = slugify_name(display_name)
        if not name:
            print(
                f"warning: empty slug at line {idx} for display_name={display_name!r}",
                file=sys.stderr,
            )
            continue

        record = {
            "name": name,
            "display_name": display_name,
            "class": CLASS_MAP[class_tag],
            "domain": current_domain or "",
            "source_domain_header": current_header or "",
            "one_liner": one_liner,
        }
        yield record, idx


def main() -> int:
    if not CONSOLIDATION.exists():
        print(f"error: {CONSOLIDATION} not found", file=sys.stderr)
        return 1

    catalog_names = existing_names(CATALOG)
    print(f"loaded {len(catalog_names)} existing names from catalog.yml")

    seen: dict[str, int] = {}
    records: list[dict] = []
    dup_warnings = 0
    excluded_catalog = 0
    total_parsed = 0

    for rec, line_no in parse_section(CONSOLIDATION):
        total_parsed += 1
        if rec["name"] in catalog_names:
            excluded_catalog += 1
            continue
        if rec["name"] in seen:
            dup_warnings += 1
            first_line = seen[rec["name"]]
            print(
                f"warning: duplicate name {rec['name']!r} at line {line_no} "
                f"(first seen at line {first_line}); keeping first",
                file=sys.stderr,
            )
            continue
        seen[rec["name"]] = line_no
        records.append(rec)

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    with OUTPUT.open("w", encoding="utf-8") as f:
        for rec in records:
            f.write(json.dumps(rec, ensure_ascii=False) + "\n")

    class_counts = Counter(r["class"] for r in records)
    domain_counts = Counter(r["domain"] for r in records)

    print()
    print(f"parsed bullets in §7: {total_parsed}")
    print(f"excluded (already in catalog.yml): {excluded_catalog}")
    print(f"duplicate-name warnings: {dup_warnings}")
    print(f"written to {OUTPUT.relative_to(ROOT)}: {len(records)}")
    print()
    print("class distribution:")
    for cls in ("lens", "frame", "model", "stance", "heuristic"):
        print(f"  {cls:<10s} {class_counts.get(cls, 0)}")
    print()
    print(f"domain distribution ({len(domain_counts)} unique, top 10):")
    for dom, n in domain_counts.most_common(10):
        print(f"  {dom:<20s} {n}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
