#!/usr/bin/env python3
"""Sync catalog.yml from library/ directory contents.

This is the single source of truth for catalog.yml generation. Run it
whenever library/ content is added, removed, or renamed.

Matching is done by *repo-relative path* (not by name), because older
(v0.2) library files store a display-name in the frontmatter `name`
field while the catalog uses a slug — matching by path is the only
stable key. Existing catalog entries are preserved by default so that
hand-curated `one_liner` text is not overwritten by frontmatter scraping.

Usage:
    python3 scripts/sync_catalog.py              # update catalog.yml (bundle)
    python3 scripts/sync_catalog.py --dry-run    # preview changes
    python3 scripts/sync_catalog.py --stats      # class/domain stats only
    python3 scripts/sync_catalog.py --overwrite  # let frontmatter override
                                                  # existing catalog entries
    python3 scripts/sync_catalog.py --source bundle   # same as no flag
    python3 scripts/sync_catalog.py --source global   # scan ~/.claude/prism/library
    python3 scripts/sync_catalog.py --source project  # scan ./.claude/prism/library
    python3 scripts/sync_catalog.py --source all      # print merged preview
                                                       # (project > global > bundle)
"""
from __future__ import annotations

import argparse
import sys
from collections import Counter, defaultdict
from pathlib import Path

import yaml

# Windows consoles (cp949, cp1252, …) choke on em-dashes and other Unicode
# used in log messages. Force UTF-8 with replacement fallback so the script
# never crashes on a print().
if sys.stdout.encoding and sys.stdout.encoding.lower() not in ("utf-8", "utf8"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
if sys.stderr.encoding and sys.stderr.encoding.lower() not in ("utf-8", "utf8"):
    sys.stderr.reconfigure(encoding="utf-8", errors="replace")

ROOT = Path(__file__).resolve().parent.parent
LIBRARY = ROOT / "library"
CATALOG = ROOT / "catalog.yml"

# 3-layer storage roots. Each layer is a (library_dir, catalog_file) pair.
# Bundle is anchored at the plugin root. Global lives under ~/.claude/prism/.
# Project lives under ./.claude/prism/ relative to CWD.
GLOBAL_ROOT = Path.home() / ".claude" / "prism"
GLOBAL_LIBRARY = GLOBAL_ROOT / "library"
GLOBAL_CATALOG = GLOBAL_ROOT / "catalog.yml"

PROJECT_ROOT = Path.cwd() / ".claude" / "prism"
PROJECT_LIBRARY = PROJECT_ROOT / "library"
PROJECT_CATALOG = PROJECT_ROOT / "catalog.yml"

LAYERS: dict[str, tuple[Path, Path, Path]] = {
    # layer name -> (layer_root, library_dir, catalog_file)
    "bundle": (ROOT, LIBRARY, CATALOG),
    "global": (GLOBAL_ROOT, GLOBAL_LIBRARY, GLOBAL_CATALOG),
    "project": (PROJECT_ROOT, PROJECT_LIBRARY, PROJECT_CATALOG),
}

# Merge precedence from broader to closer. Closer layers override broader ones.
MERGE_ORDER: list[str] = ["bundle", "global", "project"]

# Class key (singular, used in frontmatter + entries) -> library subdir (plural)
CLASS_DIRS: dict[str, str] = {
    "lens": "lenses",
    "frame": "frames",
    "model": "models",
    "stance": "stances",
    "heuristic": "heuristics",
}

# Ordered section rendering
SECTION_ORDER: list[tuple[str, str, str]] = [
    ("lens", "lenses", "LENSES — structured executable analytical procedures"),
    ("frame", "frames", "FRAMES — taxonomies / classification matrices"),
    ("model", "models", "MODELS — descriptive / predictive theoretical models"),
    ("stance", "stances", "STANCES — interpretive / critical positions"),
    ("heuristic", "heuristics", "HEURISTICS — single-rule principles (usually bundled by domain)"),
]

HEADER_COMMENT = """\
# Prism — catalog
#
# This file is the triage index. Agents read ONLY this file first,
# then selectively load individual item files based on relevance.
#
# Items are grouped by class (lens / frame / model / stance / heuristic).
# See CLASSES.md for the full taxonomy and when to pick which class.
#
# Fields:
#   name             — unique slug
#   class            — lens | frame | model | stance | heuristic
#   underlying_class — for lenses only: native | frame | model | heuristic
#                      (documents whether the lens is a native procedure or
#                       an operationalization of another class)
#   domain           — free-text domain tag
#   path             — repo-relative path to the file
#   one_liner        — triage hint, specific enough to decide on
#
# This file is generated by scripts/sync_catalog.py. Hand edits to
# existing entries' one_liner are preserved across runs unless
# --overwrite is passed.
"""


# ----------------------------------------------------------------------
# Parsing
# ----------------------------------------------------------------------
# Fields we care about for catalog generation. Any other keys in the
# frontmatter are ignored, which lets us use a tolerant line-based parser
# when the full YAML is malformed (e.g. unquoted colons in `source:`).
WANTED_FIELDS = {
    "name",
    "display_name",
    "class",
    "underlying_class",
    "domain",
    "one_liner",
}


def _shallow_parse(fm_text: str) -> dict:
    """Line-based fallback parser for top-level scalar `key: value` lines.

    Only recognizes the fields in WANTED_FIELDS. Quoted values are unquoted.
    Nested/list values are skipped. Used when strict YAML parsing fails on
    frontmatter with unquoted colons in non-relevant fields like `source:`.
    """
    out: dict = {}
    for raw_line in fm_text.splitlines():
        # Top-level keys only (no leading whitespace).
        if not raw_line or raw_line[0].isspace() or raw_line.startswith("#"):
            continue
        if ":" not in raw_line:
            continue
        key, _, rest = raw_line.partition(":")
        key = key.strip()
        if key not in WANTED_FIELDS:
            continue
        value = rest.strip()
        # Skip list / empty values (list handled by indented items we ignore).
        if not value:
            continue
        # Unquote.
        if len(value) >= 2 and value[0] == value[-1] and value[0] in ('"', "'"):
            value = value[1:-1]
        out[key] = value
    return out


def parse_frontmatter(md_path: Path) -> dict | None:
    """Extract YAML frontmatter from a markdown file. Returns None if missing."""
    try:
        text = md_path.read_text(encoding="utf-8")
    except Exception as exc:
        print(f"  [warn] cannot read {md_path}: {exc}", file=sys.stderr)
        return None
    if not text.startswith("---"):
        return None
    # Find closing fence.
    end = text.find("\n---", 3)
    if end < 0:
        return None
    fm_text = text[3:end].lstrip("\n")
    try:
        data = yaml.safe_load(fm_text)
        if isinstance(data, dict):
            return data
    except Exception:
        pass
    # Strict YAML failed — fall back to shallow line parser that only
    # pulls the fields we actually need. This rescues files with
    # unquoted colons in `source:` or similar non-essential fields.
    shallow = _shallow_parse(fm_text)
    if shallow:
        return shallow
    return None


def looks_like_slug(value: object) -> bool:
    """Cheap check: a slug uses only [a-z0-9-]."""
    if not isinstance(value, str) or not value:
        return False
    return all(c.islower() or c.isdigit() or c == "-" for c in value)


def scan_layer(layer_root: Path, library_dir: Path) -> list[dict]:
    """Scan a single layer's library/ dir and extract metadata.

    Paths in returned entries are relative to ``layer_root`` so that each
    layer's catalog.yml uses stable, layer-local paths.
    """
    items: list[dict] = []
    if not library_dir.exists():
        return items
    for cls, cls_dir in CLASS_DIRS.items():
        base = library_dir / cls_dir
        if not base.exists():
            continue

        # Non-recursive top-level .md (e.g. heuristics/general.md bundle)
        # plus recursive domain-folder .md files.
        for md in sorted(base.rglob("*.md")):
            rel_path = md.relative_to(layer_root).as_posix()
            fm = parse_frontmatter(md)
            if fm is None:
                print(f"  [warn] no frontmatter: {rel_path}", file=sys.stderr)
                continue

            fm_name = fm.get("name")
            fm_class = fm.get("class") or cls  # fall back to directory class
            fm_domain = fm.get("domain")
            fm_one_liner = fm.get("one_liner", "")
            fm_underlying = fm.get("underlying_class")

            # Figure out domain: frontmatter wins; else immediate parent folder
            # (but not 'heuristics' for the top-level bundle file).
            if not fm_domain:
                parent = md.parent.name
                fm_domain = parent if parent != cls_dir else "general"

            # Slug: prefer frontmatter name if it looks like a slug; else derive
            # from file stem. Older v0.2 files store a display-name here.
            if looks_like_slug(fm_name):
                slug = fm_name
            else:
                slug = md.stem

            entry: dict = {
                "name": slug,
                "class": fm_class,
                "domain": fm_domain,
                "path": rel_path,
                "one_liner": fm_one_liner if isinstance(fm_one_liner, str) else "",
            }
            # underlying_class is meaningful on lenses (per header comment)
            # but the existing catalog also drops it elsewhere, so we only
            # emit it for lenses, matching the current file.
            if cls == "lens" and fm_underlying:
                entry["underlying_class"] = fm_underlying

            items.append(entry)
    return items


# ----------------------------------------------------------------------
# Existing catalog
# ----------------------------------------------------------------------
def load_existing_catalog(catalog_path: Path = CATALOG) -> dict:
    """Return parsed catalog at ``catalog_path`` as a dict (empty if missing)."""
    if not catalog_path.exists():
        return {}
    with open(catalog_path, encoding="utf-8") as f:
        doc = yaml.safe_load(f)
    return doc or {}


def existing_by_path(doc: dict) -> dict[str, dict]:
    """Index existing catalog entries by their `path` field."""
    idx: dict[str, dict] = {}
    for _, section_name, _ in SECTION_ORDER:
        for entry in doc.get(section_name) or []:
            path = entry.get("path")
            if path:
                idx[path] = entry
    return idx


# ----------------------------------------------------------------------
# Rendering
# ----------------------------------------------------------------------
def format_entry(item: dict) -> list[str]:
    """Format a single catalog entry as YAML lines."""
    lines = [f"  - name: {item['name']}"]
    lines.append(f"    class: {item['class']}")
    if item.get("underlying_class"):
        lines.append(f"    underlying_class: {item['underlying_class']}")
    lines.append(f"    domain: {item['domain']}")
    lines.append(f"    path: {item['path']}")
    one_liner = item.get("one_liner") or ""
    escaped = one_liner.replace("\\", "\\\\").replace('"', '\\"')
    lines.append(f'    one_liner: "{escaped}"')
    return lines


def build_catalog_text(entries_by_section: dict[str, list[dict]]) -> str:
    """Assemble the full catalog.yml text from grouped entries."""
    out: list[str] = [HEADER_COMMENT.rstrip("\n"), ""]
    for cls_key, section_name, section_title in SECTION_ORDER:
        items = entries_by_section.get(cls_key, [])
        out.append("# " + "=" * 69)
        out.append(f"# {section_title}")
        out.append("# " + "=" * 69)
        out.append("")
        out.append(f"{section_name}:")
        if not items:
            out.append("  []")
            out.append("")
            continue

        by_domain: dict[str, list[dict]] = defaultdict(list)
        for it in items:
            by_domain[it["domain"]].append(it)

        for domain in sorted(by_domain.keys()):
            out.append(f"  # ---------- {domain} ----------")
            out.append("")
            for it in sorted(by_domain[domain], key=lambda x: x["name"]):
                out.extend(format_entry(it))
                out.append("")
        # blank line between sections
        if out[-1] != "":
            out.append("")
    return "\n".join(out).rstrip("\n") + "\n"


# ----------------------------------------------------------------------
# Merge
# ----------------------------------------------------------------------
def merge_entries(
    scanned: list[dict],
    existing_idx: dict[str, dict],
    overwrite: bool,
) -> tuple[dict[str, list[dict]], dict[str, int]]:
    """Merge scanned vs existing entries. Returns (grouped, stats)."""
    grouped: dict[str, list[dict]] = defaultdict(list)
    stats = Counter()

    scanned_paths = {it["path"] for it in scanned}

    for it in scanned:
        path = it["path"]
        existing = existing_idx.get(path)
        if existing and not overwrite:
            # Preserve hand-curated entries. Keep the existing fields as-is,
            # but ensure the class bucket matches the scanned class so it
            # ends up in the right section.
            cls = existing.get("class") or it["class"]
            merged = dict(existing)
            merged["class"] = cls
            grouped[cls].append(merged)
            stats["preserved"] += 1
        else:
            grouped[it["class"]].append(it)
            if existing:
                stats["overwritten"] += 1
            else:
                stats["added"] += 1

    stats["removed"] = sum(
        1 for path in existing_idx if path not in scanned_paths
    )
    return grouped, stats


# ----------------------------------------------------------------------
# Main
# ----------------------------------------------------------------------
def print_stats(items: list[dict]) -> None:
    cls_counts = Counter(it["class"] for it in items)
    dom_counts = Counter(it["domain"] for it in items)
    print(f"Total: {len(items)} items")
    print("\nBy class:")
    for k in ["lens", "frame", "model", "stance", "heuristic"]:
        print(f"  {k}: {cls_counts.get(k, 0)}")
    print("\nBy domain (top 20):")
    for d, c in dom_counts.most_common(20):
        print(f"  {d}: {c}")


def _sync_single_layer(layer: str, args) -> int:
    """Scan one layer and write (or dry-run) its catalog."""
    layer_root, library_dir, catalog_path = LAYERS[layer]

    if layer in ("global", "project") and not library_dir.exists():
        print(
            f"[{layer}] library dir not found: {library_dir} — nothing to do",
            file=sys.stderr,
        )
        return 0

    scanned = scan_layer(layer_root, library_dir)

    existing_doc = load_existing_catalog(catalog_path)
    existing_idx = existing_by_path(existing_doc)

    grouped, stats = merge_entries(scanned, existing_idx, args.overwrite)

    print(f"[{layer}] Scanned: {len(scanned)} items in {library_dir}")
    print(f"[{layer}] Existing catalog: {len(existing_idx)} entries")
    print(f"  added: {stats.get('added', 0)}")
    print(f"  preserved: {stats.get('preserved', 0)}")
    print(f"  overwritten: {stats.get('overwritten', 0)}")
    print(f"  removed (in catalog but not library): {stats.get('removed', 0)}")

    if stats.get("removed", 0):
        removed_paths = [
            p for p in existing_idx
            if p not in {it["path"] for it in scanned}
        ]
        print("  removed paths:")
        for p in removed_paths[:10]:
            print(f"    - {p}")

    text = build_catalog_text(grouped)

    if args.dry_run:
        print(f"\n=== [{layer}] Dry run — not writing ===")
        print(f"Target: {catalog_path}")
        print(f"Output size: {len(text)} bytes, {text.count(chr(10))} lines")
        return 0

    catalog_path.parent.mkdir(parents=True, exist_ok=True)
    catalog_path.write_text(text, encoding="utf-8")
    total_written = sum(len(v) for v in grouped.values())
    print(f"\n[{layer}] Catalog updated: {catalog_path}")
    print(f"  {total_written} entries written")
    return 0


def _collect_all_layers() -> dict[str, list[dict]]:
    """Scan bundle + global + project, skipping layers whose library is missing.

    Returns a mapping layer_name -> list of entries. Missing global/project
    layers are noted on stderr but not treated as errors.
    """
    per_layer: dict[str, list[dict]] = {}
    for layer in MERGE_ORDER:
        layer_root, library_dir, _ = LAYERS[layer]
        if layer in ("global", "project") and not library_dir.exists():
            print(
                f"[{layer}] library dir not found: {library_dir} — skipping",
                file=sys.stderr,
            )
            per_layer[layer] = []
            continue
        per_layer[layer] = scan_layer(layer_root, library_dir)
    return per_layer


def _merge_layers(per_layer: dict[str, list[dict]]) -> list[dict]:
    """Merge per-layer entries with precedence project > global > bundle.

    Collisions are resolved by the closer layer; each override is logged to
    stderr.
    """
    merged: dict[str, tuple[str, dict]] = {}  # name -> (layer, entry)
    for layer in MERGE_ORDER:  # broader first, closer last so it wins
        for it in per_layer.get(layer, []):
            name = it["name"]
            if name in merged:
                prev_layer, _ = merged[name]
                if prev_layer != layer:
                    print(
                        f"WARN: '{name}' overridden by {layer} layer "
                        f"(was in {prev_layer})",
                        file=sys.stderr,
                    )
            merged[name] = (layer, it)
    return [entry for _, entry in merged.values()]


def _run_all_preview(args) -> int:
    """--source all: build a merged in-memory view and print to stdout."""
    per_layer = _collect_all_layers()
    merged_items = _merge_layers(per_layer)

    # Group by class for rendering.
    grouped: dict[str, list[dict]] = defaultdict(list)
    for it in merged_items:
        grouped[it["class"]].append(it)

    text = build_catalog_text(grouped)

    if args.dry_run:
        print(
            "[all] --dry-run is a no-op (all mode never writes to disk)",
            file=sys.stderr,
        )
    # Print merged preview to stdout.
    sys.stdout.write(text)
    return 0


def _print_stats_per_layer(per_layer: dict[str, list[dict]]) -> None:
    """Emit per-layer class breakdown in addition to combined stats."""
    for layer in MERGE_ORDER:
        if layer not in per_layer:
            continue
        items = per_layer[layer]
        print(f"\n[{layer}] Total: {len(items)} items")
        if not items:
            continue
        cls_counts = Counter(it["class"] for it in items)
        print(f"[{layer}] By class:")
        for k in ["lens", "frame", "model", "stance", "heuristic"]:
            print(f"  {k}: {cls_counts.get(k, 0)}")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("--dry-run", action="store_true",
                        help="Do not write catalog.yml; print summary only")
    parser.add_argument("--stats", action="store_true",
                        help="Print class/domain statistics and exit")
    parser.add_argument("--overwrite", action="store_true",
                        help="Let frontmatter override existing catalog entries")
    parser.add_argument("--source", choices=["bundle", "global", "project", "all"],
                        default="bundle",
                        help="Which storage layer to sync. bundle (default) = "
                             "./library/+./catalog.yml; global = "
                             "~/.claude/prism/; project = ./.claude/prism/; "
                             "all = merged preview to stdout (no writes)")
    args = parser.parse_args()

    # --stats path: preserve legacy single-layer stats when --source is absent
    # (i.e. default bundle) so `sync_catalog.py --stats` output is byte-stable.
    # When combined with an explicit --source, show per-layer stats.
    if args.stats:
        # Detect whether --source was explicitly provided by the user.
        explicit_source = any(
            a == "--source" or a.startswith("--source=")
            for a in sys.argv[1:]
        )
        if not explicit_source:
            layer_root, library_dir, _ = LAYERS["bundle"]
            scanned = scan_layer(layer_root, library_dir)
            print_stats(scanned)
            return 0
        if args.source == "all":
            per_layer = _collect_all_layers()
        else:
            layer_root, library_dir, _ = LAYERS[args.source]
            if args.source in ("global", "project") and not library_dir.exists():
                print(
                    f"[{args.source}] library dir not found: {library_dir}",
                    file=sys.stderr,
                )
                per_layer = {args.source: []}
            else:
                per_layer = {args.source: scan_layer(layer_root, library_dir)}
        combined = [it for items in per_layer.values() for it in items]
        print_stats(combined)
        _print_stats_per_layer(per_layer)
        return 0

    if args.source == "all":
        return _run_all_preview(args)

    return _sync_single_layer(args.source, args)


if __name__ == "__main__":
    raise SystemExit(main())
